### PR TITLE
C++ compatibility

### PR DESCRIPTION
**Pull request by maciejandrzejewski-digica**
Add C++ compatibility flag to allow compilation without errors when using C++ parent project.

### CODE REVIEW

**Review by xioTechnologies — COMMENTED** [review]
https://github.com/xioTechnologies/Fusion/pull/78/commits/6220b972dd2f19af7fabc632784ccff54aea339c Why is this a name collision?  Where is the other instance of this project name?

**Comment by maciejandrzejewski-digica** [comment]
> Why is this a name collision? Where is the other instance of this project name?

It is a mistake. Same name for Project and for Library name which is not an error.

**Comment by xioTechnologies** [comment]
We have fixed C++ compatibility in https://github.com/xioTechnologies/Fusion/commit/dde922f72a717aa251ee1c18d242f57bb6bc2de2 and tests were added to a temporary branch to verify the fix ([results here](https://github.com/xioTechnologies/Fusion/actions/runs/4143620029)).  We decided that it would not be appropriate merge C++ tests or examples into the main branch of this C library.

**Comment by LazaroFilm** [comment]
That last update seems to have solved the C++ issue. Now all I need to do is rename the `Fusion` folder to `src` and it's Arduino library compatible.

**Pull request closed without merging**
